/*
  BANK SOAL GURU
  Tambahkan soal dengan pola yang sama sampai 30 butir pada setiap bank.
  type: 'pg' | 'pgk' | 'essay'
  answer untuk pg adalah index pilihan (0-based), pgk adalah array index,
  essay memakai keywords yang semuanya wajib ditemukan pada jawaban siswa.
*/
const questionBanks = {
  utama: [
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Seorang siswa diminta menyusun jadwal belajar mingguan. Ia memisahkan tugas berdasarkan mata pelajaran, lalu memecah setiap tugas menjadi bagian-bagian kecil seperti "membaca materi", "mengerjakan latihan", dan "meninjau ulang". Aspek berpikir komputasional yang paling tepat menggambarkan langkah ini adalah...', options: ['Abstraksi, karena ia menyederhanakan tugas', 'Dekomposisi, karena ia memecah tugas besar menjadi bagian kecil', 'Pengenalan pola, karena ia mengenali kemiripan tugas', 'Algoritma, karena ia menyusun instruksi langkah demi langkah'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Dalam merancang aplikasi peta digital, pengembang hanya menampilkan jalan utama, nama tempat penting, dan rute, tanpa menampilkan detail seperti jenis pohon di pinggir jalan atau warna cat rumah. Keputusan ini adalah penerapan aspek berpikir komputasional berupa...', options: ['Dekomposisi, karena peta dipecah menjadi lapisan-lapisan', 'Abstraksi, karena hanya informasi relevan yang ditampilkan', 'Pengenalan pola, karena rute yang mirip dikelompokkan', 'Algoritma, karena rute dihitung secara berurutan'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Saat memeriksa hasil ulangan beberapa kelas, seorang guru menyadari bahwa siswa yang sering salah pada soal cerita matematika juga cenderung salah pada soal cerita fisika, sehingga guru menduga akar masalahnya sama, yaitu kemampuan memahami soal cerita. Proses berpikir guru ini paling menggambarkan aspek...', options: ['Dekomposisi', 'Abstraksi', 'Pengenalan pola', 'Algoritma'], answer: 2 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah tim sedang mengembangkan aplikasi absensi sekolah. Mereka membagi pekerjaan menjadi modul login, modul pencatatan kehadiran, dan modul laporan, lalu masing-masing dikerjakan oleh anggota berbeda secara paralel. Manfaat utama penerapan dekomposisi dalam kasus ini adalah...', options: ['Mempercepat pengerjaan karena tiap bagian bisa dikerjakan terpisah dan lebih fokus', 'Membuat aplikasi otomatis bebas dari kesalahan (bug)', 'Menghilangkan kebutuhan pengujian aplikasi', 'Mengurangi jumlah anggota tim yang dibutuhkan'], answer: 0 },
    { type: 'pg', difficulty: 'sulit', point: 3, question: 'Dua kelompok siswa diminta membuat program penghitung nilai rata-rata. Kelompok 1 langsung menulis kode tanpa merancang alur, sedangkan Kelompok 2 terlebih dahulu mengidentifikasi input, proses, dan output yang benar-benar dibutuhkan sebelum menulis kode. Jika keduanya kelak diberi soal yang lebih kompleks, prediksi paling logis mengenai hasil kerja mereka adalah...', options: ['Kelompok 1 akan lebih cepat karena tidak membuang waktu merancang', 'Kelompok 2 akan lebih siap karena penerapan abstraksi membantu mereka fokus pada hal yang relevan sebelum menulis kode', 'Tidak ada perbedaan karena keduanya sama-sama menulis kode', 'Kelompok 1 lebih unggul karena langsung praktik tanpa teori'], answer: 1 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Perhatikan langkah membuat teh berikut: (1) didihkan air, (2) masukkan teh, (3) tuang ke gelas, (4) aduk gula. Jika urutan langkah (2) dan (3) ditukar, hal yang paling mungkin terjadi adalah...', options: ['Tidak berpengaruh apa pun karena urutan bebas', 'Hasil akhir berubah karena teh belum tercelup air panas saat dituang', 'Proses menjadi lebih cepat', 'Air menjadi lebih dingin'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah algoritma dikatakan tidak efektif apabila...', options: ['Menghasilkan output yang benar tetapi lambat dieksekusi', 'Memiliki langkah yang jelas namun tidak pernah berhenti untuk sebagian input', 'Ditulis dalam bahasa pemrograman yang jarang digunakan', 'Membutuhkan banyak baris kode'], answer: 1 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Diberikan data belum terurut: 8, 3, 10, 5, 2. Untuk mencari angka 5, algoritma yang bisa langsung digunakan tanpa proses tambahan adalah...', options: ['Binary search, karena datanya cukup pendek', 'Linear search, karena tidak memerlukan data dalam keadaan terurut', 'Binary search, karena lebih cepat', 'Keduanya sama-sama bisa langsung dipakai'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Data berikut sudah terurut: 2, 5, 8, 12, 16, 20, 23. Jika binary search digunakan untuk mencari angka 12, elemen tengah yang pertama kali diperiksa adalah...', options: ['2', '8', '12', '20'], answer: 2 },
    { type: 'pg', difficulty: 'sulit', point: 3, question: 'Data berikut sudah terurut: 3, 7, 11, 15, 19, 23, 27, 31. Binary search digunakan untuk mencari angka 19. Berapa kali proses pembandingan dengan elemen tengah dilakukan hingga angka tersebut ditemukan?', options: ['1 kali', '2 kali', '3 kali', '4 kali'], answer: 2 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Data: 4, 2, 7, 1. Setelah satu kali proses penukaran elemen berdekatan (langkah pertama bubble sort dari kiri), susunan datanya menjadi...', options: ['2, 4, 7, 1', '4, 2, 7, 1', '4, 7, 2, 1', '2, 7, 4, 1'], answer: 0 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Data: 6, 9, 2, 4. Menggunakan selection sort (mencari elemen terkecil lalu menukarnya ke posisi awal), susunan data setelah langkah pertama adalah...', options: ['2, 9, 6, 4', '6, 2, 9, 4', '2, 4, 6, 9', '6, 9, 4, 2'], answer: 0 },
    { type: 'pg', difficulty: 'sulit', point: 3, question: 'Data: 5, 1, 4, 2, 8. Menggunakan insertion sort, setelah tiga langkah pertama (elemen ke-2, ke-3, dan ke-4 telah disisipkan pada posisinya masing-masing), susunan data menjadi...', options: ['1, 2, 4, 5, 8', '1, 4, 2, 5, 8', '1, 4, 5, 2, 8', '2, 1, 4, 5, 8'], answer: 0 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah sistem informasi akademik menyimpan 10.000 data siswa dalam keadaan tidak terurut berdasarkan NIS, dan pencarian hanya dilakukan sesekali. Algoritma pencarian yang paling masuk akal digunakan tanpa harus mengurutkan data terlebih dahulu adalah...', options: ['Binary search, karena selalu lebih cepat', 'Linear search, karena tidak memerlukan proses pengurutan tambahan yang memakan biaya', 'Binary search, karena datanya banyak', 'Kedua algoritma sama-sama tidak bisa digunakan'], answer: 1 },
    { type: 'pg', difficulty: 'sulit', point: 3, question: 'Sebuah aplikasi marketplace memiliki jutaan data produk yang terus diperbarui secara acak setiap detik. Jika aplikasi ini ingin menerapkan binary search agar pencarian lebih cepat, tantangan utama yang harus diatasi terlebih dahulu adalah...', options: ['Menghapus separuh data agar lebih sedikit', 'Menjaga agar data tetap dalam keadaan terurut meskipun terus berubah', 'Mengubah seluruh data menjadi angka', 'Menyimpan seluruh data dalam bentuk stack'], answer: 1 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Sebuah e-commerce menyediakan fitur "urutkan berdasarkan harga". Ketika pengguna memilih fitur ini, proses yang terjadi di balik layar adalah penerapan dari...', options: ['Algoritma searching, karena mencari produk termurah', 'Algoritma sorting, karena menyusun ulang seluruh data produk berdasarkan harga', 'Struktur data queue, karena produk diproses satu per satu', 'Struktur data stack, karena produk terakhir ditampilkan pertama'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah sistem leaderboard game memperbarui peringkat pemain setiap kali ada skor baru masuk, dengan jumlah pemain sangat besar. Jika sistem mengurutkan ulang seluruh data setiap kali hanya satu skor baru masuk, dampak yang paling mungkin terjadi adalah...', options: ['Sistem menjadi lebih efisien karena data selalu terurut', 'Sistem menjadi lambat karena pengurutan ulang berulang kali hanya untuk perubahan kecil', 'Tidak ada dampak karena proses sorting selalu instan', 'Leaderboard menjadi tidak akurat'], answer: 1 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Tumpukan piring di dapur, di mana piring yang terakhir diletakkan adalah piring yang pertama kali diambil untuk digunakan, adalah ilustrasi dari struktur data...', options: ['Queue, karena mengikuti urutan datang', 'Stack, karena mengikuti prinsip LIFO', 'Queue, karena mengikuti prinsip LIFO', 'Stack, karena mengikuti prinsip FIFO'], answer: 1 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Antrean kendaraan di pintu tol, di mana kendaraan yang pertama datang adalah yang pertama dilayani, adalah ilustrasi dari struktur data...', options: ['Stack, karena prinsip FIFO', 'Queue, karena prinsip FIFO', 'Stack, karena prinsip LIFO', 'Queue, karena prinsip LIFO'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah sistem memproses permintaan cetak dokumen menggunakan stack, bukan queue. Dampak yang akan dirasakan pengguna jika sistem ini diterapkan pada printer bersama adalah...', options: ['Dokumen tercetak sesuai urutan pengiriman, adil bagi semua pengguna', 'Dokumen yang paling terakhir dikirim justru tercetak lebih dulu, sehingga tidak adil bagi yang mengirim lebih awal', 'Tidak ada dampak karena stack dan queue bekerja sama persis', 'Semua dokumen tercetak secara bersamaan'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Dilakukan urutan operasi berikut pada stack kosong: push(A), push(B), pop(), push(C). Isi stack dari bawah ke atas sekarang adalah...', options: ['A, B, C', 'A, C', 'A, B', 'C, A'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Dilakukan urutan operasi berikut pada stack kosong: push(5), push(9), peek(), push(1). Susunan stack dari bawah ke atas sekarang adalah...', options: ['5, 9, 1', '5, 1, 9', '9, 5, 1', '5, 9'], answer: 0 },
    { type: 'pg', difficulty: 'sulit', point: 3, question: 'Sebuah program melakukan urutan operasi berikut pada stack kosong: push(1), push(2), pop(), push(3), push(4), pop(), pop(). Elemen yang tersisa di dalam stack setelah seluruh operasi ini adalah...', options: ['1', '3', '4', 'Kosong (stack habis)'], answer: 0 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Dilakukan urutan operasi berikut pada queue kosong: enqueue(A), enqueue(B), dequeue(), enqueue(C). Isi queue dari depan ke belakang sekarang adalah...', options: ['A, B, C', 'B, C', 'A, C', 'C, B'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Dilakukan urutan operasi berikut pada queue kosong: enqueue(7), enqueue(2), enqueue(9). Jika front() dipanggil setelahnya, nilai yang dikembalikan adalah...', options: ['7', '2', '9', 'Kosong'], answer: 0 },
    { type: 'pg', difficulty: 'sulit', point: 3, question: 'Sebuah sistem antrean loket melakukan urutan operasi berikut pada queue kosong: enqueue(A), enqueue(B), enqueue(C), dequeue(), enqueue(D), dequeue(). Pelanggan yang berada di posisi paling depan queue setelah seluruh operasi ini adalah...', options: ['A', 'B', 'C', 'D'], answer: 2 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Aplikasi pengolah kata menyimpan setiap perubahan teks yang dilakukan pengguna. Saat pengguna menekan "undo" berkali-kali, perubahan yang dibatalkan selalu perubahan paling baru terlebih dahulu. Struktur data yang paling tepat mendasari fitur ini adalah...', options: ['Queue, karena FIFO', 'Stack, karena LIFO', 'Queue, karena LIFO', 'Stack, karena FIFO'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah compiler bahasa pemrograman menggunakan stack untuk memeriksa kesesuaian tanda kurung buka dan tutup dalam kode, misalnya `( [ { } ] )`. Alasan stack cocok digunakan untuk kasus ini adalah...', options: ['Karena tanda kurung yang dibuka terakhir harus ditutup terlebih dahulu, sesuai prinsip LIFO', 'Karena tanda kurung harus diproses sesuai urutan kedatangan, sesuai prinsip FIFO', 'Karena stack dapat menyimpan data dalam jumlah tak terbatas', 'Karena stack selalu lebih cepat daripada queue untuk semua kasus'], answer: 0 },
    { type: 'pg', difficulty: 'mudah', point: 1, question: 'Sistem pemesanan tiket online melayani pembeli sesuai urutan siapa yang lebih dulu menekan tombol "beli", agar adil bagi semua pembeli. Struktur data yang paling sesuai untuk kasus ini adalah...', options: ['Stack, karena LIFO', 'Queue, karena FIFO', 'Stack, karena FIFO', 'Queue, karena LIFO'], answer: 1 },
    { type: 'pg', difficulty: 'sedang', point: 2, question: 'Sebuah call center menggunakan queue untuk mengatur giliran penelepon yang akan dilayani. Suatu hari sistem diam-diam diubah menjadi stack tanpa sepengetahuan manajemen. Dampak yang paling mungkin dikeluhkan pelanggan adalah...', options: ['Penelepon yang menunggu paling lama justru dilayani paling akhir', 'Semua penelepon dilayani secara bersamaan', 'Tidak ada dampak karena stack dan queue identik', 'Penelepon otomatis terputus'], answer: 0 }
  ],
  remedi: [
    { type: 'pg', question: 'Alat untuk mengetik huruf dan angka disebut ...', options: ['Mouse', 'Keyboard', 'Scanner', 'Speaker'], answer: 1 },
    { type: 'pg', question: 'Contoh mesin pencari di internet adalah ...', options: ['Google', 'Windows', 'Excel', 'Bluetooth'], answer: 0 },
    { type: 'pgk', question: 'Pilih perangkat input.', options: ['Mouse', 'Keyboard', 'Monitor', 'Scanner'], answer: [0, 1, 3] },
    { type: 'essay', question: 'Sebutkan kepanjangan dari LAN.', keywords: ['local area network'] },
    { type: 'pg', question: 'Angka 1 dalam sistem biner ditulis sebagai ...', options: ['0', '1', '10', '11'], answer: 1 },
    { type: 'pg', question: 'Program untuk menjelajah internet disebut ...', options: ['Browser', 'Compiler', 'Driver', 'Database'], answer: 0 },
    { type: 'pgk', question: 'Pilih contoh media penyimpanan.', options: ['SSD', 'Flashdisk', 'RAM', 'Hard disk'], answer: [0, 1, 3] },
    { type: 'essay', question: 'Apa fungsi utama mouse pada komputer?', keywords: ['menggerakkan', 'kursor'] },
    { type: 'pg', question: 'Satuan terkecil data digital adalah ...', options: ['Byte', 'Bit', 'Pixel', 'Hertz'], answer: 1 },
    { type: 'pg', question: 'Etika berkomunikasi di internet disebut ...', options: ['Netiket', 'Netral', 'Nirkabel', 'Netrum'], answer: 0 }
  ],
  pengayaan: [
    { type: 'pg', question: 'Struktur data yang menerapkan prinsip LIFO adalah ...', options: ['Queue', 'Stack', 'Tree', 'Graph'], answer: 1 },
    { type: 'pg', question: 'Protokol yang umum digunakan untuk mengakses halaman web adalah ...', options: ['HTTP', 'FTP', 'SMTP', 'SSH'], answer: 0 },
    { type: 'pgk', question: 'Pilih semua contoh ancaman keamanan siber.', options: ['Phishing', 'Malware', 'Backup', 'Social engineering'], answer: [0, 1, 3] },
    { type: 'essay', question: 'Jelaskan mengapa kata sandi perlu dibuat kuat.', keywords: ['keamanan', 'akses'] },
    { type: 'pg', question: 'Kompleksitas pencarian binary search pada kondisi umum adalah ...', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], answer: 1 },
    { type: 'pg', question: 'Basis data relasional menyimpan data dalam bentuk ...', options: ['Tabel', 'Audio', 'Video', 'Animasi'], answer: 0 },
    { type: 'pgk', question: 'Pilih praktik pemrograman yang baik.', options: ['Nama variabel jelas', 'Menguji program', 'Mengabaikan error', 'Membuat komentar seperlunya'], answer: [0, 1, 3] },
    { type: 'essay', question: 'Apa tujuan utama enkripsi data?', keywords: ['melindungi', 'informasi'] },
    { type: 'pg', question: 'IPv4 memiliki panjang alamat sebesar ... bit.', options: ['16', '32', '64', '128'], answer: 1 },
    { type: 'pg', question: 'Diagram yang umum dipakai untuk menggambarkan alur algoritma adalah ...', options: ['Flowchart', 'Spreadsheet', 'Mind map', 'Storyboard'], answer: 0 }
  ]
};

const app = document.getElementById('app');
const state = {
  screen: 'login', student: { name: '', className: '' }, mode: null, questions: [], answers: [], doubts: [], current: 0,
  endAt: 0, timerId: null, score: 0, mainScore: null, remedialScore: null, enrichmentScore: null,
  remedialAttempts: 0, enrichmentTaken: false, finished: false
};

const shuffle = (items) => [...items].sort(() => Math.random() - 0.5);
const esc = (value) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const modeLabel = { utama: 'Soal Utama', remedi: 'Soal Remedi', pengayaan: 'Soal Pengayaan' };
const modeTime = { utama: 50, remedi: 30, pengayaan: 30 };
const defaultPoints = { pg: 1, pgk: 2, essay: 3 };

function header(session = false) {
  return `<header class="topbar"><div class="brand"><div class="brand-mark">✦</div><div>SUMATIF X<small>Informatika • Kelas 10</small></div></div>${session ? `<div class="session-chip"><span class="session-dot"></span>${esc(state.student.name)}</div>` : ''}</header>`;
}

function renderLogin() {
  app.innerHTML = `${header()}<main class="page login-page"><section class="login-layout"><div class="login-intro"><div class="eyebrow">Ulangan Sumatif • 2026</div><h1>Berpikir komputasional, dimulai dari sini.</h1><p>Siapkan fokus terbaikmu. Baca setiap soal dengan teliti, lalu kerjakan dengan tenang sampai selesai.</p><div class="exam-facts"><div><strong>${questionBanks.utama.length}</strong><span>Contoh soal utama</span></div><div><strong>50′</strong><span>Durasi</span></div><div><strong>82</strong><span>KKM</span></div></div></div><form class="login-form" id="loginForm"><h2>Selamat datang</h2><p>Isi identitas untuk masuk ke ruang ujian.</p><label class="field">Nama lengkap<input name="name" required autocomplete="name" placeholder="Contoh: Aulia Putri" /></label><label class="field">Kelas<input name="className" required placeholder="Contoh: X-1" /></label><div class="error" id="loginError"></div><button class="primary-btn full" type="submit">Masuk ke ruang ujian&nbsp; →</button></form></section></main>`;
  document.getElementById('loginForm').addEventListener('submit', (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    state.student.name = data.get('name').trim(); state.student.className = data.get('className').trim();
    if (!state.student.name || !state.student.className) return;
    state.screen = 'dashboard'; render();
  });
}

function renderDashboard() {
  app.innerHTML = `${header(true)}<main class="page"><div class="dashboard-head"><div><div class="welcome-label">Halo, ${esc(state.student.name)} 👋</div><h1>Siap untuk tantangan hari ini?</h1><p>Kelas ${esc(state.student.className)} · Ulangan Sumatif Informatika</p></div></div><div class="dashboard-grid"><section class="panel main-exam"><span class="badge">Wajib dikerjakan</span><h2>Ujian Utama</h2><p>Uji pemahamanmu tentang konsep dasar Informatika, algoritma, jaringan, dan keamanan digital.</p><div class="exam-summary"><div><strong>${questionBanks.utama.length}</strong><span>Contoh soal</span></div><div><strong>50 menit</strong><span>Waktu tersedia</span></div><div><strong>82</strong><span>Nilai KKM</span></div></div><button class="primary-btn" id="startMain">Mulai kerjakan soal&nbsp; →</button></section><aside class="panel rules"><h3>Petunjuk singkat</h3><div class="rule"><b>01</b><span>Pilih jawaban paling tepat. Soal kompleks dapat memiliki lebih dari satu jawaban.</span></div><div class="rule"><b>02</b><span>Kamu bebas berpindah nomor melalui panel navigasi di sebelah kiri.</span></div><div class="rule"><b>03</b><span>Gunakan tanda <strong>Ragu-ragu</strong> agar soal mudah ditemukan kembali.</span></div><div class="rule"><b>04</b><span>Nilai akan muncul otomatis setelah kamu mengumpulkan jawaban.</span></div></aside></div></main>`;
  document.getElementById('startMain').addEventListener('click', () => startExam('utama'));
}

function startExam(mode) {
  state.mode = mode; state.questions = mode === 'remedi' ? shuffle(questionBanks.remedi) : mode === 'pengayaan' ? shuffle(questionBanks.pengayaan) : [...questionBanks.utama];
  state.answers = Array(state.questions.length).fill(null); state.doubts = Array(state.questions.length).fill(false); state.current = 0;
  state.endAt = Date.now() + modeTime[mode] * 60 * 1000; state.screen = 'exam'; render();
}

function formatTime() { const remaining = Math.max(0, state.endAt - Date.now()); const seconds = Math.floor(remaining / 1000); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
function isAnswered(answer) { return Array.isArray(answer) ? answer.length > 0 : answer !== null && answer !== ''; }
function answerClass(index) { return state.doubts[index] ? 'doubt' : isAnswered(state.answers[index]) ? 'done' : ''; }

function renderExam() {
  const question = state.questions[state.current]; const answer = state.answers[state.current];
  const typeLabel = question.type === 'pg' ? 'Pilihan Ganda' : question.type === 'pgk' ? 'Pilihan Ganda Kompleks' : 'Essay / Isian';
  const difficultyLabel = question.difficulty ? `${question.difficulty[0].toUpperCase()}${question.difficulty.slice(1)} • ${question.point ?? defaultPoints[question.type]} poin` : '';
  const nav = state.questions.map((_, index) => `<button class="question-number ${index === state.current ? 'active' : ''} ${answerClass(index)}" data-index="${index}">${index + 1}</button>`).join('');
  const questionBody = question.type === 'essay' ? `<textarea class="essay-answer" id="essayAnswer" placeholder="Ketik jawabanmu di sini...">${esc(answer || '')}</textarea><div class="hint">Jawaban dinilai otomatis berdasarkan kata kunci yang ditentukan guru.</div>` : `<div class="options">${question.options.map((option, index) => { const selected = question.type === 'pgk' ? (answer || []).includes(index) : answer === index; return `<label class="option ${selected ? 'selected' : ''}"><input type="${question.type === 'pgk' ? 'checkbox' : 'radio'}" name="answer" value="${index}" ${selected ? 'checked' : ''}><span class="option-letter">${String.fromCharCode(65 + index)}</span><span class="option-text">${esc(option)}</span></label>`; }).join('')}</div>`;
  app.innerHTML = `<div class="exam-layout"><aside class="exam-sidebar"><div class="brand"><div class="brand-mark">✦</div><div>SUMATIF X<small>Ruang Ujian</small></div></div><h2 class="exam-title">${modeLabel[state.mode]}</h2><p class="exam-subtitle">${esc(state.student.name)} · ${esc(state.student.className)}</p><div class="timer-box"><span>Sisa waktu</span><div class="timer" id="timer">${formatTime()}</div></div><div class="question-nav-label"><span>Navigasi soal</span><span>${state.questions.length} soal</span></div><div class="question-grid">${nav}</div><div class="legend"><div class="legend-row"><i class="legend-dot"></i>Belum dikerjakan</div><div class="legend-row"><i class="legend-dot green"></i>Sudah dikerjakan</div><div class="legend-row"><i class="legend-dot yellow"></i>Ragu-ragu</div></div></aside><section class="exam-content"><div class="exam-topbar"><div class="student">Peserta: <strong>${esc(state.student.name)}</strong></div><button class="ghost-btn" id="submitExam">Kumpulkan</button></div><main class="question-area"><div class="question-meta"><span class="badge">${typeLabel}${difficultyLabel ? ` • ${difficultyLabel}` : ''}</span><span class="question-count">Soal ${state.current + 1} dari ${state.questions.length}</span></div><h1 class="question-text">${esc(question.question)}</h1>${questionBody}<div class="question-actions"><button class="ghost-btn ${state.doubts[state.current] ? 'doubt-btn active' : ''}" id="toggleDoubt">${state.doubts[state.current] ? '★ Ditandai ragu' : '☆ Tandai ragu-ragu'}</button><div class="action-right"><button class="ghost-btn" id="prevQuestion" ${state.current === 0 ? 'disabled' : ''}>← Sebelumnya</button><button class="primary-btn" id="nextQuestion">${state.current === state.questions.length - 1 ? 'Selesai' : 'Berikutnya →'}</button></div></div></main></section></div>`;
  bindExamEvents(); startTimer();
}

function saveCurrentAnswer() {
  const question = state.questions[state.current];
  if (question.type === 'essay') state.answers[state.current] = document.getElementById('essayAnswer').value.trim();
  else if (question.type === 'pgk') state.answers[state.current] = [...document.querySelectorAll('input[name="answer"]:checked')].map((input) => Number(input.value));
  else { const checked = document.querySelector('input[name="answer"]:checked'); state.answers[state.current] = checked ? Number(checked.value) : null; }
}
function bindExamEvents() {
  document.querySelectorAll('.question-number').forEach((button) => button.addEventListener('click', () => { saveCurrentAnswer(); state.current = Number(button.dataset.index); renderExam(); }));
  document.querySelectorAll('input[name="answer"]').forEach((input) => input.addEventListener('change', saveCurrentAnswer));
  document.getElementById('essayAnswer')?.addEventListener('input', saveCurrentAnswer);
  document.getElementById('toggleDoubt').addEventListener('click', () => { state.doubts[state.current] = !state.doubts[state.current]; renderExam(); });
  document.getElementById('prevQuestion').addEventListener('click', () => { if (state.current > 0) { saveCurrentAnswer(); state.current -= 1; renderExam(); } });
  document.getElementById('nextQuestion').addEventListener('click', () => { saveCurrentAnswer(); if (state.current === state.questions.length - 1) submitExam(); else { state.current += 1; renderExam(); } });
  document.getElementById('submitExam').addEventListener('click', () => { saveCurrentAnswer(); if (confirm('Kumpulkan jawaban sekarang?')) submitExam(); });
}
function startTimer() { clearInterval(state.timerId); state.timerId = setInterval(() => { const timer = document.getElementById('timer'); if (!timer) return clearInterval(state.timerId); timer.textContent = formatTime(); if (Date.now() >= state.endAt) { clearInterval(state.timerId); saveCurrentAnswer(); submitExam(true); } }, 1000); }

function scoreExam() {
  let earned = 0; let possible = 0;
  state.questions.forEach((question, index) => { const answer = state.answers[index]; const point = Number(question.point ?? defaultPoints[question.type] ?? 1); possible += point; let correct = false; if (question.type === 'essay') { const text = String(answer || '').toLowerCase(); correct = (question.keywords || []).every((keyword) => text.includes(keyword.toLowerCase())); } else if (question.type === 'pg') correct = answer === question.answer; else { const actual = [...(answer || [])].sort().join(','); const expected = [...question.answer].sort().join(','); correct = actual === expected; } if (correct) earned += point; });
  return possible ? Math.round((earned / possible) * 100) : 0;
}
function submitExam(auto = false) { clearInterval(state.timerId); state.score = scoreExam(); if (state.mode === 'utama') state.mainScore = state.score; if (state.mode === 'remedi') state.remedialScore = state.score; if (state.mode === 'pengayaan') state.enrichmentScore = state.score; state.screen = 'result'; state.autoSubmitted = auto; render(); }

function renderResult() {
  const score = state.score; const passed = score >= 82; const isMain = state.mode === 'utama';
  let content = '';
  if (isMain && !passed) content = `<h3>Waktunya menguatkan lagi</h3><p>Nilai ulangan asli kamu masih di bawah KKM 82. Gunakan kesempatan remedi untuk mencoba kembali.</p><div class="score-comparison"><div class="score-item"><strong>${state.mainScore}</strong><span>Nilai ulangan asli</span></div><div class="score-item"><strong>-</strong><span>Nilai remedi</span></div></div><div class="result-actions">${state.remedialAttempts < 3 ? `<button class="primary-btn" id="nextPath">Mulai remedi (${state.remedialAttempts + 1}/3)&nbsp; →</button>` : '<button class="primary-btn" id="finish">Lihat ringkasan akhir</button>'}</div>`;
  else if (isMain && passed) content = `<h3>Selamat, kamu lulus!</h3><p>Nilai utama kamu sudah melewati KKM. Pengayaan tersedia sebagai tantangan tambahan dan bisa memberi bonus nilai.</p><div class="result-actions"><button class="primary-btn" id="nextPath">Ambil pengayaan&nbsp; →</button><button class="ghost-btn" id="finish">Lewati</button></div>`;
  else if (state.mode === 'remedi') content = `<h3>${passed ? 'Remedi berhasil!' : 'Tetap semangat belajar'}</h3><p>${passed ? 'Nilai remedi sudah mencapai KKM dan langsung menjadi nilai akhir yang digunakan.' : 'Nilai remedi masih di bawah KKM. Periksa kembali materi dan gunakan kesempatan yang tersedia.'}</p><div class="score-comparison"><div class="score-item"><strong>${state.mainScore}</strong><span>Nilai ulangan asli</span></div><div class="score-item"><strong>${state.remedialScore}</strong><span>Nilai remedi</span></div><div class="score-item"><strong>${passed ? state.remedialScore : state.mainScore}</strong><span>Nilai akhir sementara</span></div></div><div class="result-actions">${!passed && state.remedialAttempts < 3 ? `<button class="primary-btn" id="nextPath">Coba lagi (${state.remedialAttempts + 1}/3)&nbsp; →</button>` : '<button class="primary-btn" id="finish">Lanjut ke ringkasan&nbsp; →</button>'}</div>`;
  else content = `<h3>${score > 90 ? 'Bonus berhasil didapat!' : 'Pengayaan selesai'}</h3><p>${score > 90 ? 'Nilai pengayaan kamu di atas 90. Satu poin bonus akan ditambahkan ke nilai sumatif utama.' : 'Terima kasih sudah menantang dirimu. Nilai pengayaan tercatat sebagai hasil tambahan.'}</p><div class="result-actions"><button class="primary-btn" id="finish">Lihat ringkasan akhir&nbsp; →</button></div>`;
  app.innerHTML = `${header(true)}<main class="result-wrap"><section class="result-hero"><div class="result-icon">${passed ? '✓' : '!'}</div><h1>${modeLabel[state.mode]} selesai</h1><p>${state.autoSubmitted ? 'Waktu habis, jawaban telah dikumpulkan otomatis.' : 'Jawabanmu telah berhasil dikumpulkan.'}</p><div class="score">${score}<small> / 100</small></div></section><section class="result-card">${content}</section></main>`;
  document.getElementById('nextPath')?.addEventListener('click', () => { if (state.mode === 'utama') { if (state.score < 82) state.remedialAttempts = 1; else state.enrichmentTaken = true; startExam(state.score < 82 ? 'remedi' : 'pengayaan'); } else if (state.mode === 'remedi') { state.remedialAttempts += 1; startExam('remedi'); } });
  document.getElementById('finish')?.addEventListener('click', () => { state.finished = true; state.screen = 'closing'; render(); });
}

function renderClosing() {
  const bonus = state.enrichmentTaken && state.enrichmentScore > 90 ? 1 : 0; const baseScore = state.remedialScore >= 82 ? state.remedialScore : (state.mainScore || 0); const finalScore = Math.min(100, baseScore + bonus);
  app.innerHTML = `${header(true)}<main class="result-wrap"><section class="close-note"><div class="result-icon">✓</div><h2>Perjalanan ujian selesai</h2><p>Berikut perbandingan nilai dan nilai akhir kamu.</p><div class="score" style="color: var(--green-700); margin: 24px 0 10px;">${finalScore}<small style="color:var(--muted);"> / 100</small></div><div class="score-comparison"><div class="score-item"><strong>${state.mainScore ?? '-'}</strong><span>Nilai ulangan asli</span></div><div class="score-item"><strong>${state.remedialScore ?? '-'}</strong><span>Nilai remedi</span></div><div class="score-item"><strong>${state.enrichmentScore ?? '-'}</strong><span>Nilai pengayaan</span></div></div><p>${bonus ? 'Bonus pengayaan: +1 poin.' : 'Tidak ada bonus pengayaan.'}</p><div class="result-card"><strong>Jangan lupa catat nilai kalian masing-masing!</strong></div><button class="primary-btn" id="closeApp">Close</button></section></main>`;
  document.getElementById('closeApp').addEventListener('click', () => { state.screen = 'login'; state.student = { name: '', className: '' }; state.mainScore = null; state.remedialScore = null; state.enrichmentScore = null; state.remedialAttempts = 0; state.enrichmentTaken = false; render(); });
}
function render() { if (state.screen === 'login') renderLogin(); else if (state.screen === 'dashboard') renderDashboard(); else if (state.screen === 'exam') renderExam(); else if (state.screen === 'result') renderResult(); else renderClosing(); }
render();
